pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

name: Minded_0.1$(Rev:.r)
    
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack    
    versioningScheme: byBuildNumber
    projects: |
      **/Minded.Extensions.Caching.csproj
      **/Minded.Extensions.Configuration.csproj
      **/Minded.Extensions.Decorator.csproj
      **/Minded.Extensions.Exception.csproj
      **/Minded.Extensions.Logging.csproj
      **/Minded.Extensions.OData.csproj
      **/Minded.Extensions.Transaction.csproj
      **/Minded.Extensions.Validation.csproj
      **/Minded.Extensions.Validation.Abstractions.csproj
      **/Minded.Extensions.WebApi.csproj
      **/Minded.Framework.CQRS.csproj
      **/Minded.Framework.CQRS.Abstractions.csproj
      **/Minded.Framework.Mediator.csproj
      **/Minded.Framework.Mediator.Abstractions.csproj

- task: DotNetCoreCLI@2
  displayName: 'NuGet Push Packages'
  inputs:
    command: custom
    custom: nuget
    arguments: 'push $(Build.ArtifactStagingDirectory)/*.nupkg -s https://api.nuget.org/v3/index.json -k $(NugetApiKey)'

- task: DotNetCoreCLI@2
  displayName: 'NuGet Push Symbols'
  inputs:
    command: custom
    custom: nuget
    arguments: 'push $(Build.ArtifactStagingDirectory)/*.snupkg -s https://api.nuget.org/v3/index.json -k $(NugetApiKey)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  enabled: false
  condition: succeededOrFailed()
